import axios from 'axios';
import dotenv from 'dotenv';
import { Order } from '../models/index.js';
import https from 'https';

dotenv.config();

const httpsAgent = new https.Agent({ rejectUnauthorized: false });

const API_URL = 'https://gateway.starbee.dev';
const MERCHANT_ID = process.env.STARBEE_MERCHANT_ID || 'dummy_merchant_id';
const SECRET_KEY = process.env.STARBEE_SECRET_KEY || 'dummy_secret_key';

const monCashService = {
  /**
   * Obtient un token d'accès Starbee
   */
  getAccessToken: async () => {
    try {
      const response = await axios.post(`${API_URL}/api/merchant/token/`, {
        merchant_id: MERCHANT_ID,
        secret_key: SECRET_KEY
      }, { httpsAgent });

      if (response.data && response.data.success && response.data.data) {
        return response.data.data.token;
      }
      throw new Error('No token in response');
    } catch (error) {
      console.error('Starbee Auth Error:', error.response?.data || error.message);
      throw new Error(`Auth Fail: ${error.message}`);
    }
  },

  /**
   * @param {string|number} orderId - ID de la commande
   * @param {number} amount - Montant total
   * @param {string} returnUrl - URL de retour (optionnel)
   * @returns {Promise<{redirectUrl: string, token: string}>} Données de redirection
   */
  createPayment: async (orderId, amount, returnUrl = null) => {
    try {
      const token = await monCashService.getAccessToken();

      // Récupération de l'email client si possible
      let customerEmail = 'client@htfasil.com';
      let customerName = 'Client HTFasil';
      
      if (!String(orderId).startsWith('BOOST_')) {
          try {
             const order = await Order.findByPk(orderId, { include: ['user'] });
             if (order && order.user) {
                 customerEmail = order.user.email || customerEmail;
                 customerName = order.user.name || customerName;
             }
          } catch(e) {
             console.warn('Could not fetch user info for payment', e.message);
          }
      }

      const paymentData = {
        amount: Number(amount),
        reference_id: `${String(orderId)}_${Date.now()}`,
        customer_email: customerEmail,
        customer_name: customerName,
        description: `Paiement commande ${orderId}`,
        return_url: returnUrl
      };

      console.log('Sending Starbee Payment:', paymentData);

      const response = await axios.post(`${API_URL}/api/merchant/payments/moncash/`, paymentData, {
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        },
        httpsAgent
      });

      if (response.data && response.data.success && response.data.data) {
        return {
           redirectUrl: response.data.data.redirect_url,
           token: response.data.data.id // Transaction UUID generated by Starbee
        };
      }
      
      throw new Error('Invalid response from gateway');

    } catch (error) {
      console.error('Starbee CreatePayment Error:', error.response?.data || error.message);
      let msg = error.response?.data?.message || error.message;
      throw new Error(`API Fail: ${msg}`);
    }
  },

  /**
   * Vérifie le statut d'un paiement via l'UUID de transaction
   * @param {string} transactionId - ID de transaction Starbee
   * @returns {Promise<object>} Détails du paiement
   */
  retrieveOrder: async (transactionId) => {
    try {
      const token = await monCashService.getAccessToken();
      const response = await axios.get(`${API_URL}/api/merchant/payments/moncash/verify/${transactionId}/`, {
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        },
        httpsAgent
      });
      
      if (response.data && response.data.success && response.data.data) {
          const status = response.data.data.status; // pending | completed | failed
          return {
             status: status === 'completed' ? 'successful' : status, // Mappé pour rétrocompatibilité
             amount: response.data.data.amount,
             transaction_id: response.data.data.transaction_id || transactionId,
             reference_id: response.data.data.reference_id
          };
      }
      return null;
    } catch (error) {
      console.error('Starbee RetrieveOrder Error:', error.response?.data || error.message);
      return null;
    }
  },

  /**
   * Alias pour rétrocompatibilité
   */
  retrieveTransaction: async (transactionToken) => {
    return await monCashService.retrieveOrder(transactionToken);
  }
};

export default monCashService;
